### PR TITLE
Lower deployment target to iOS 8.0, matching Eureka

### PR DESCRIPTION
**Pull request by MrAlek**

### CODE REVIEW

**Comment by MrAlek** [comment]
@m-revetria Sure thing, I'll fix it.

**Comment by MrAlek** [comment]
Updated the podspec.

**Comment by MrAlek** [comment]
@m-revetria Any updates on this, #7 and #8 ?

**Comment by m-revetria** [comment]
Hi @MrAlek thanks for updating this! Sorry for the long time to get back to you :)

**Comment by MrAlek** [comment]
No worries, we're still using Eureka. Keep up the good work! :)

**Pull request merged**
